### PR TITLE
Added cURL support.

### PR DESCRIPTION
**Pull request by LiveG-Technologies**
Yeah, it's a full cURL installer.

### CODE REVIEW

**Comment by Spannner** [comment]
whoops accidentally closed it for a moment there sorry

**Comment by LiveG-Technologies** [comment]
Try this in an empty folder:

`curl -sS https://raw.githubusercontent.com/neontribe/untangled-2017/60122605c06e80037281c7be5e01ffa25cf567bd/curl.sh | bash`

**Comment by Spannner** [comment]
(Infinite loop)
`arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_EPOLL=1 -Ibundled/zeromq/include -Ibundled/zeromq/tweetnacl/src -Ibundled/zeromq/tweetnacl/contrib/randombytes -Ibundled -I/usr/include/python3.4m -c bundled/zeromq/src/tcp.cpp -o build/temp.linux-armv7l-3.4/bundled/zeromq/src/tcp.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_EPOLL=1 -Ibundled/zeromq/include -Ibundled/zeromq/tweetnacl/src -Ibundled/zeromq/tweetnacl/contrib/randombytes -Ibundled -I/usr/include/python3.4m -c bundled/zeromq/src/tcp_listener.cpp -o build/temp.linux-armv7l-3.4/bundled/zeromq/src/tcp_listener.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++`

I don't know much about cURL but I'm pretty sure this is bad

**Comment by LiveG-Technologies** [comment]
Nice! Odd error. That happened to me. One of the guys said it wasn't infinite because the file names were changing, so I let it roll.

**Comment by Stansbridge** [comment]
Git clone works OK for this

**Pull request closed without merging**
